language: python
python:
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"

install:
    - pip install tox flake8

script:
    - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')
    - flake8 watdo tests
